---
  - name: JUNOS SOFTWARE
    hosts: all
    gather_facts: no

    tasks:
      - name: JUNOS BACKUP
        junos_config:
          backup: yes
          backup_options:
            filename: "{{ inventory_hostname }}.txt"
            dir_path: /u000/Juniper_Backup
