---
  - name: VYOS SOFTWARE
    hosts: all
    gather_facts: no

    tasks:
      - name: VYOS BACKUP
        vyos_config:
          backup: yes
          backup_options:
            filename: "{{ inventory_hostname }}_VMR.txt"
            dir_path: /u000/Flexware_Backup

