---
  - name: JUNOS FACTS & CONFIG
    hosts: all
    gather_facts: no

    tasks:
      - name: collect default set of facts and configuration
        junos_facts:
          port: 22
        register: JUNOS_Output


      - name: PRINT JUNOS RESULT
        debug:
          msg: "{{ JUNOS_Output }} "
